### ISSUE TITLE
DetachedThreadLocal vs ThreadLocal

### ISSUE THREAD

**Issue by felixbarny** [raphw/weak-lock-free#3]
What are the advantages of a DetachedThreadLocal over a java.lang.ThreadLocal? Is it that there's not the danger of memory/class loader leaks?

**Comment by tylerbenson** [comment]
I'm wondering the same thing... @felixbarny what did you end up using?

**Comment by codefromthecrypt** [comment]
I suppose if you ignore most advanced methods, the fact that it has a clean() method is the big one. if your calling framework has a shutdown, it can clean its thread local values allowing the classloader to be unloaded.

**Comment by raphw** [comment]
The major difference is that you can access the state of Thread A from Thread B only by owning a reference to the instance of `Thread` A. This is not possible in thread locals. Also, the mentioned leakage avoidance as you do not store anything in a foreign instance.
