### ISSUE TITLE
calling sysout on map results in printing objects address rather than contents[map entries]

### ISSUE THREAD

**Issue by FuncGuy** [raphw/weak-lock-free#7]
Hi Rafael,
@raphw 
I was playing with weak concurrent map and i found that calling System.out.println(weakConcurrentMap) prints objects address rather than key value pairs this may be least bug/issue even i can't say this is bug what do you think?

Thanks

**Comment by raphw** [comment]
Note that this would require iterating over entries and therefore cause eviction, so it can be rather expensive. Rather extract the underlying map and print that one.

**Comment by FuncGuy** [comment]
you mean this?

 WeakConcurrentMap<String, String> map = new WeakConcurrentMap<String, String>(true);
 map.put("hello", "world");
 Field  field = WeakConcurrentMap.class.getDeclaredField("target");
 field.setAccessible(true);
 ConcurrentMap<String, String> concurrentMap = (ConcurrentMap<String, String>) field.get(map);
 System.out.println(concurrentMap);

**Comment by FuncGuy** [comment]
in this case we have to override tostring() method in WeakKey class to print key's real value.

**Comment by raphw** [comment]
Ah, you are right. Would probably be easiest to just add toString methods where it's appropriate for those who want to use it. If you send me a PR, I can merge and release it.

**Comment by FuncGuy** [comment]
thanks I will raise a PR soon....

**Comment by FuncGuy** [comment]
@raphw done!!
https://github.com/raphw/weak-lock-free/pull/8

**Comment by raphw** [comment]
Just released 0.16 with this fix.
